### ISSUE TITLE
Issue after update to 4.6.0 (PF2E)

### ISSUE THREAD

**Issue by malevolentmaple** [MrPrimate/tokenizer#217]
Tokenizer won't open (as GM), silently fails and opens standard image upload interface, error logged in console is as follows: 

foundry.mjs:23855 Error: Error thrown in hooked function '' for hook 'renderCharacterSheetPF2e'. html.querySelector is not a function
[Detected 2 packages: vtta-tokenizer(4.6.0), system:pf2e(7.8.0)]
    at Hooks.onError (foundry.mjs:23854:24)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)
    at #call (foundry.mjs:23836:36)
    at Hooks.callAll (foundry.mjs:23791:17)
    at CharacterSheetPF2e._callHooks (foundry.mjs:37444:15)
    at CharacterSheetPF2e._render (foundry.mjs:37406:10)
    at async CharacterSheetPF2e._render (foundry.mjs:38130:5)
    at async CharacterSheetPF2e._render (foundry.mjs:38728:5)
    at async maintainFocusInRender (pf2e.mjs:1338:332904)
    at async CharacterSheetPF2e._render (pf2e.mjs:1374:140814)Caused by: TypeError: html.querySelector is not a function
[Detected 2 packages: vtta-tokenizer(4.6.0), system:pf2e(7.8.0)]
    at Object.fn (hooks.js:390:1)
    at #call (foundry.mjs:23832:20)
    at Hooks.callAll (foundry.mjs:23791:17)
    at CharacterSheetPF2e._callHooks (foundry.mjs:37444:15)
    at CharacterSheetPF2e._render (foundry.mjs:37406:10)
    at async CharacterSheetPF2e._render (foundry.mjs:38130:5)
    at async CharacterSheetPF2e._render (foundry.mjs:38728:5)
    at async maintainFocusInRender (pf2e.mjs:1338:332904)
    at async CharacterSheetPF2e._render (pf2e.mjs:1374:140814)

I rolled back to 4.5.7 and it behaves as expected.

**Comment by MrPrimate** [comment]
> Even with 4.6.1 i'm having the same issue, same error. Running pf1e.
> 
> It works the first time i use tokenizer, and the interface opens. But later it goes into error and opens the file browser

Fix out shortly for this.

**Comment by MrPrimate** [comment]
> It looks like the same issue happens as well if you have a token open in combat, progress a turn and then try open tokenizer. This looks pretty niche after double checking. It is only broken so long as the token is already open while progressing through the turns.
> 
> foundry.mjs:23855 Error: Error thrown in hooked function '' for hook 'renderActorSheetSFRPGCharacter'. key.querySelector is not a function

Is this using the Starfinder system?

**Comment by MrPrimate** [comment]
> > > It looks like the same issue happens as well if you have a token open in combat, progress a turn and then try open tokenizer. This looks pretty niche after double checking. It is only broken so long as the token is already open while progressing through the turns.
> > > foundry.mjs:23855 Error: Error thrown in hooked function '' for hook 'renderActorSheetSFRPGCharacter'. key.querySelector is not a function
> > 
> > 
> > Is this using the Starfinder system?
> 
> Yes! I was trying it in a few systems.

Can you try with the latest release and see if it is fixed for you?
